plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}

android {
    namespace 'com.nerfeai'
    compileSdk 35
    ndkVersion '27.2.12479018'

    defaultConfig {
        applicationId 'com.nerfeai'
        minSdk 26
        targetSdk 35
        versionCode 1
        versionName '1.0'

        ndk {
            abiFilters 'arm64-v8a'
        }

        externalNativeBuild {
            cmake {
                cppFlags '-std=c++17'
                arguments '-DANDROID_STL=c++_shared'
            }
        }
    }

    androidResources {
        noCompress += ['gguf']
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = '17'
    }

    externalNativeBuild {
        cmake {
            path file('src/main/cpp/CMakeLists.txt')
            version '3.22.1'
        }
    }

    buildTypes {
        debug {
            minifyEnabled false
        }

        release {
            minifyEnabled false
	    signingConfig signingConfigs.debug
        }
    }
}
