package com.nerfeai.update

import com.nerfeai.BuildConfig

data class ReleaseInfo(
    val versionName: String,
    val versionCode: Int,
    val notes: String
) {

    companion object {

        fun current(): ReleaseInfo {

            return ReleaseInfo(
                versionName =
                    BuildConfig.VERSION_NAME,

                versionCode =
                    BuildConfig.VERSION_CODE,

                notes =
                    getUpdateNotes()
            )
        }

        private fun getUpdateNotes(): String {

            /*
             * UPDATE_NOTES will be generated by Gradle.
             *
             * This fallback keeps the application safe if
             * the Gradle field has not been configured yet.
             */
            return try {

                val field =
                    BuildConfig::class.java
                        .getField("UPDATE_NOTES")

                field.get(null) as? String
                    ?: "Bug fixes and improvements."

            } catch (_: Exception) {

                "Bug fixes and improvements."
            }
        }
    }
}